import React from "react";
import { Col, Container, Row, Table } from "react-bootstrap";

const Pricing = () => {
  return (
    <div>
      <div id="about-us" className="bg-secondary">
        <Container>
          <Row>
            <Col md={12}>
              <div className="pt-5 pb-5">
                <h2 className="text-center text-white">Pricing</h2>
              </div>
            </Col>
          </Row>
        </Container>
      </div>

      <div id="pricing" className="pt-3 pb-3 pt-md-5 pb-md-5">
        <Container>
          <Row className="justify-content-center">
            <Col md={8}>
              <Table bordered className="text-center border-primary">
                <tbody>
                  <tr>
                    <th>Grade</th>
                    <td>M20</td>
                    <td>M25</td>
                  </tr>
                  <tr>
                    <th>Rate</th>
                    <td>4300</td>
                    <td>4500</td>
                  </tr>
                </tbody>
              </Table>
              <p className="">
                *** Any further increase in the price of raw materials such as
                cement, blue metals (12mm & 20mm), sand, admixture, Diesel, Govt
                Taxes, water shall be reimbursed to us at actual cost.
              </p>
            </Col>
          </Row>
        </Container>
      </div>

      <div id="pricing-1" className="pt-3 pb-3 pt-md-5 pb-md-5 bg-light">
        <Container>
          <Row>
            <Col md={12}>
              <div className="">
                <h2 className="pt-2 pb-2">Terms and Conditions:</h2>

                <ul>
                  <li>
                    The rate mentioned above is inclusive of basic cost of RMC,
                    and GST 18%, basic price, transportation of concrete,
                    pumping, but does not include formwork, leveling,
                    vibrations, finishing, curing etc. Any increase in Sales Tax
                    and new fresh Government levies, if any shall be reimbursed
                    to us at actual.
                  </li>
                  <li>
                    RMC supplied will be tested as per bureau of Indian Standard
                    Norms.
                  </li>
                  <li>
                    The current cost of diesel is Rs.85.4 /- per liter. Any
                    increase in the cost of diesel shall be reimbursed to us.
                  </li>
                  <li>
                    The supplies will be made on volumetric basis as per reports
                    generated by our computer and will be charged accordingly.
                  </li>
                  <li>
                    Please note that the rates mentioned above are uniform for
                    both pumping and dumping.
                  </li>
                  <li>
                    We assure you of the quality of concrete. Test results for 7
                    and 28 days of compressive strength would provide.
                  </li>
                  <li>
                    It is suggested to keep tarpaulins at site to protect
                    concrete from the sudden fall of rain. It is highly
                    recommended to use wet gunny bags to cover the concrete
                    after 4-5 hours and sprinkle water lightly to avoid any loss
                    of water due to evaporation
                  </li>
                </ul>
              </div>
            </Col>
          </Row>
        </Container>
      </div>

      <div id="pricing-2" className="pt-3 pb-3 pt-md-5 pb-md-5">
          <Container>
              <Row>
                  <Col md={12}>
                      <div className="">
                          <h2 className="pt-2 pb-2">Payment Terms</h2>
                          <ul>
                              <li>Immediate payment by Cheque.</li>
                              <li>Payment should be made by way of Demand Draft /Cheque drawn on a scheduled bank in favor of “GRADEMAX CONCRETE” payable at Bangalore.</li>
                          </ul>
                      </div>
                  </Col>
              </Row>
          </Container>
      </div>

      <div id="pricing-3" className="pt-3 pb-3 pt-md-5 pb-md-5 bg-light">
          <Container>
              <Row>
                  <Col md={12}>
                      <div className="">
                          <h2 className="pt-2 pb-2">Delivery</h2>
                          <ul>
                              <li>We would request you to give us a schedule of 2 to 3 day’s concrete requirement in advance so as to enable smooth execution of the operation. We shall accommodate your valued orders on shorter notice also, subject to availability of the requested time/date.</li>
                              <li>We will not be able to supply during traffic restriction hours, you will provide us the permission from the Govt. to ply the trucks from our plant to your sites and incase of any expenses through fine/ penalty charged by the traffic police, the same will be at your account.</li>
                              <li>Our responsibility is to dispatch the required qty of RMC to your site. Once the RMC reaches the site, the pouring of RMC can be done at your advice.</li>
                              <li> We do not owe any responsibility for damage to any equipment or injury or any loss to human on this account. Our scope is limited to supply of RMC and rest responsibility lies with customer who had placed the order for the supply of RMC.</li>
                              <li>Service will be available 24 X 7</li>
                          </ul>
                      </div>
                  </Col>
              </Row>
          </Container>
      </div>
    </div>
  );
};

export default Pricing;
